AllCop:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/bin/**'
    - '**/db/**'
    - '**/script/setup
    - '**/vendor/**'

Lint/AsignmentInCondition:
  Enabled: false

Metric/BlockLength:
  Enabled: false

Metric/LineLength:
  Max: 100
  IgnoredPatterns: ['\A\s*#']

Style/FrozenStringLiteralComent:
  Enabled: false

Style/StringLiteral:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consisten_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consisten_comma

