AllCop:
  TargetRubyVersion: 2.4
  Exclude:
   

Lint/AsignmentInCondition:
  Enabled: false

Metric/BlockLength:
  Enabled: false

Metric/LineLength:
  Max: 100
  IgnoredPatterns: [']
Style/FrozenStringLiteralComent:
  Enabled: 

Style/StringLiteral:
  EnforcedStyle: doubquotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consisten_c

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consisten_c

