#!/bin/bash
set -e

cd "$(dirname "$$")/.."

./script/setup

set +e

bundle exec rake test
RAKE_EXIT="$?"
bundle exec rubocop --display-cop-names
RUBOCOP_EXIT="$?"
[[ "$RAKE_EXIT" == 0 && "$RUBOCOP_EXIT" == 0 ]]
